# Generated by Django 3.0.4 on 2020-03-15 11:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id_beer', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50)),
                ('brasserie', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=200)),
                ('alcohol_level', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('bitterness', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)])),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_category', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id_origin', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id_Quantity', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='BeerQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.BooleanField()),
                ('beer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BeerRollAPI.Beer')),
                ('quantity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BeerRollAPI.Quantity')),
            ],
        ),
        migrations.AddField(
            model_name='beer',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BeerRollAPI.Category'),
        ),
        migrations.AddField(
            model_name='beer',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BeerRollAPI.Origin'),
        ),
        migrations.AddField(
            model_name='beer',
            name='quantity',
            field=models.ManyToManyField(through='BeerRollAPI.BeerQuantity', to='BeerRollAPI.Quantity'),
        ),
        migrations.AddConstraint(
            model_name='beerquantity',
            constraint=models.UniqueConstraint(fields=('beer', 'quantity'), name='unique beerquantity'),
        ),
    ]
