# Generated by Django 3.0.4 on 2020-03-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeerRollAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beerquantity',
            name='stock',
            field=models.BooleanField(default=True),
        ),
    ]
