# Generated by Django 3.0.4 on 2020-03-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeerRollAPI', '0002_auto_20200315_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beerquantity',
            name='stock',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
